server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: transaction_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
        - id: account_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/accounts/**
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: true